### ISSUE TITLE
reduced improvement in testing/training accuracy

### ISSUE THREAD

**Issue by abhilash97** [abhilash97/Hyperspectral-Image-Learning#2]
k-Fold cross validation might increase the accuracy to an extent. Required to be implemented

**Comment by abhilash97** [comment]
Push your hsiClassifier_testing.py onto the master. ONLY this file, not any other.

**Comment by gPats** [comment]
k

**Comment by gPats** [comment]
Ok

**Comment by abhilash97** [comment]
with k ~ 100, i was once getting 71% accuracy in a certain fold(didn't completely exec.). So, increasing k might be of some help. Ok
